; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -argpromotion < %s | FileCheck %s --check-prefixes=ALL,ARGPROMOTION
; RUN: opt -S -passes=argpromotion < %s | FileCheck %s --check-prefixes=ALL,ARGPROMOTION
; RUN: opt -S -passes=attributor -aa-pipeline='basic-aa' -attributor-disable=false -attributor-max-iterations-verify -attributor-max-iterations=3 < %s | FileCheck %s --check-prefixes=ALL,ATTRIBUTOR
; Test that we only promote arguments when the caller/callee have compatible
; function attrubtes.

target triple = "x86_64-unknown-linux-gnu"

; This should promote
define internal fastcc void @callee_avx512_legal512_prefer512_call_avx512_legal512_prefer512(<8 x i64>* %arg, <8 x i64>* readonly %arg1) #0 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer512_call_avx512_legal512_prefer512
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]], <8 x i64> [[ARG1_VAL:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    store <8 x i64> [[ARG1_VAL]], <8 x i64>* [[ARG]]
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer512_call_avx512_legal512_prefer512
; ATTRIBUTOR-SAME: (<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
<<<<<<< HEAD
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]], align 32
||||||| parent of 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0:%.*]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG:%.*]], align 32
=======
; ATTRIBUTOR-NEXT:    store <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64>* [[ARG]], align 32
>>>>>>> 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = load <8 x i64>, <8 x i64>* %arg1
  store <8 x i64> %tmp, <8 x i64>* %arg
  ret void
}

define void @avx512_legal512_prefer512_call_avx512_legal512_prefer512(<8 x i64>* %arg) #0 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@avx512_legal512_prefer512_call_avx512_legal512_prefer512
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ARGPROMOTION-NEXT:    call void @llvm.memset.p0i8.i64(i8* align 32 [[TMP3]], i8 0, i64 32, i1 false)
; ARGPROMOTION-NEXT:    [[TMP_VAL:%.*]] = load <8 x i64>, <8 x i64>* [[TMP]]
; ARGPROMOTION-NEXT:    call fastcc void @callee_avx512_legal512_prefer512_call_avx512_legal512_prefer512(<8 x i64>* [[TMP2]], <8 x i64> [[TMP_VAL]])
; ARGPROMOTION-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@avx512_legal512_prefer512_call_avx512_legal512_prefer512
; ATTRIBUTOR-SAME: (<8 x i64>* nocapture writeonly [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP_0_VECBLEND:%.*]] = select <8 x i1> <i1 true, i1 true, i1 true, i1 true, i1 false, i1 false, i1 false, i1 false>, <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64> undef
; ATTRIBUTOR-NEXT:    call fastcc void @callee_avx512_legal512_prefer512_call_avx512_legal512_prefer512(<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[TMP2]])
; ATTRIBUTOR-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = alloca <8 x i64>, align 32
  %tmp2 = alloca <8 x i64>, align 32
  %tmp3 = bitcast <8 x i64>* %tmp to i8*
  call void @llvm.memset.p0i8.i64(i8* align 32 %tmp3, i8 0, i64 32, i1 false)
  call fastcc void @callee_avx512_legal512_prefer512_call_avx512_legal512_prefer512(<8 x i64>* %tmp2, <8 x i64>* %tmp)
  %tmp4 = load <8 x i64>, <8 x i64>* %tmp2, align 32
  store <8 x i64> %tmp4, <8 x i64>* %arg, align 2
  ret void
}

; This should promote
define internal fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal512_prefer256(<8 x i64>* %arg, <8 x i64>* readonly %arg1) #1 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer256_call_avx512_legal512_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]], <8 x i64> [[ARG1_VAL:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    store <8 x i64> [[ARG1_VAL]], <8 x i64>* [[ARG]]
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer256_call_avx512_legal512_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
<<<<<<< HEAD
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]], align 32
||||||| parent of 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0:%.*]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG:%.*]], align 32
=======
; ATTRIBUTOR-NEXT:    store <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64>* [[ARG]], align 32
>>>>>>> 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = load <8 x i64>, <8 x i64>* %arg1
  store <8 x i64> %tmp, <8 x i64>* %arg
  ret void
}

define void @avx512_legal512_prefer256_call_avx512_legal512_prefer256(<8 x i64>* %arg) #1 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@avx512_legal512_prefer256_call_avx512_legal512_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ARGPROMOTION-NEXT:    call void @llvm.memset.p0i8.i64(i8* align 32 [[TMP3]], i8 0, i64 32, i1 false)
; ARGPROMOTION-NEXT:    [[TMP_VAL:%.*]] = load <8 x i64>, <8 x i64>* [[TMP]]
; ARGPROMOTION-NEXT:    call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal512_prefer256(<8 x i64>* [[TMP2]], <8 x i64> [[TMP_VAL]])
; ARGPROMOTION-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@avx512_legal512_prefer256_call_avx512_legal512_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* nocapture writeonly [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP_0_VECBLEND:%.*]] = select <8 x i1> <i1 true, i1 true, i1 true, i1 true, i1 false, i1 false, i1 false, i1 false>, <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64> undef
; ATTRIBUTOR-NEXT:    call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal512_prefer256(<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[TMP2]])
; ATTRIBUTOR-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = alloca <8 x i64>, align 32
  %tmp2 = alloca <8 x i64>, align 32
  %tmp3 = bitcast <8 x i64>* %tmp to i8*
  call void @llvm.memset.p0i8.i64(i8* align 32 %tmp3, i8 0, i64 32, i1 false)
  call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal512_prefer256(<8 x i64>* %tmp2, <8 x i64>* %tmp)
  %tmp4 = load <8 x i64>, <8 x i64>* %tmp2, align 32
  store <8 x i64> %tmp4, <8 x i64>* %arg, align 2
  ret void
}

; This should promote
define internal fastcc void @callee_avx512_legal512_prefer512_call_avx512_legal512_prefer256(<8 x i64>* %arg, <8 x i64>* readonly %arg1) #1 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer512_call_avx512_legal512_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]], <8 x i64> [[ARG1_VAL:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    store <8 x i64> [[ARG1_VAL]], <8 x i64>* [[ARG]]
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer512_call_avx512_legal512_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
<<<<<<< HEAD
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]], align 32
||||||| parent of 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0:%.*]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG:%.*]], align 32
=======
; ATTRIBUTOR-NEXT:    store <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64>* [[ARG]], align 32
>>>>>>> 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = load <8 x i64>, <8 x i64>* %arg1
  store <8 x i64> %tmp, <8 x i64>* %arg
  ret void
}

define void @avx512_legal512_prefer512_call_avx512_legal512_prefer256(<8 x i64>* %arg) #0 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@avx512_legal512_prefer512_call_avx512_legal512_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ARGPROMOTION-NEXT:    call void @llvm.memset.p0i8.i64(i8* align 32 [[TMP3]], i8 0, i64 32, i1 false)
; ARGPROMOTION-NEXT:    [[TMP_VAL:%.*]] = load <8 x i64>, <8 x i64>* [[TMP]]
; ARGPROMOTION-NEXT:    call fastcc void @callee_avx512_legal512_prefer512_call_avx512_legal512_prefer256(<8 x i64>* [[TMP2]], <8 x i64> [[TMP_VAL]])
; ARGPROMOTION-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@avx512_legal512_prefer512_call_avx512_legal512_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* nocapture writeonly [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP_0_VECBLEND:%.*]] = select <8 x i1> <i1 true, i1 true, i1 true, i1 true, i1 false, i1 false, i1 false, i1 false>, <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64> undef
; ATTRIBUTOR-NEXT:    call fastcc void @callee_avx512_legal512_prefer512_call_avx512_legal512_prefer256(<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[TMP2]])
; ATTRIBUTOR-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = alloca <8 x i64>, align 32
  %tmp2 = alloca <8 x i64>, align 32
  %tmp3 = bitcast <8 x i64>* %tmp to i8*
  call void @llvm.memset.p0i8.i64(i8* align 32 %tmp3, i8 0, i64 32, i1 false)
  call fastcc void @callee_avx512_legal512_prefer512_call_avx512_legal512_prefer256(<8 x i64>* %tmp2, <8 x i64>* %tmp)
  %tmp4 = load <8 x i64>, <8 x i64>* %tmp2, align 32
  store <8 x i64> %tmp4, <8 x i64>* %arg, align 2
  ret void
}

; This should promote
define internal fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal512_prefer512(<8 x i64>* %arg, <8 x i64>* readonly %arg1) #0 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer256_call_avx512_legal512_prefer512
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]], <8 x i64> [[ARG1_VAL:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    store <8 x i64> [[ARG1_VAL]], <8 x i64>* [[ARG]]
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer256_call_avx512_legal512_prefer512
; ATTRIBUTOR-SAME: (<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
<<<<<<< HEAD
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]], align 32
||||||| parent of 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0:%.*]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG:%.*]], align 32
=======
; ATTRIBUTOR-NEXT:    store <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64>* [[ARG]], align 32
>>>>>>> 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = load <8 x i64>, <8 x i64>* %arg1
  store <8 x i64> %tmp, <8 x i64>* %arg
  ret void
}

define void @avx512_legal512_prefer256_call_avx512_legal512_prefer512(<8 x i64>* %arg) #1 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@avx512_legal512_prefer256_call_avx512_legal512_prefer512
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ARGPROMOTION-NEXT:    call void @llvm.memset.p0i8.i64(i8* align 32 [[TMP3]], i8 0, i64 32, i1 false)
; ARGPROMOTION-NEXT:    [[TMP_VAL:%.*]] = load <8 x i64>, <8 x i64>* [[TMP]]
; ARGPROMOTION-NEXT:    call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal512_prefer512(<8 x i64>* [[TMP2]], <8 x i64> [[TMP_VAL]])
; ARGPROMOTION-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@avx512_legal512_prefer256_call_avx512_legal512_prefer512
; ATTRIBUTOR-SAME: (<8 x i64>* nocapture writeonly [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP_0_VECBLEND:%.*]] = select <8 x i1> <i1 true, i1 true, i1 true, i1 true, i1 false, i1 false, i1 false, i1 false>, <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64> undef
; ATTRIBUTOR-NEXT:    call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal512_prefer512(<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[TMP2]])
; ATTRIBUTOR-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = alloca <8 x i64>, align 32
  %tmp2 = alloca <8 x i64>, align 32
  %tmp3 = bitcast <8 x i64>* %tmp to i8*
  call void @llvm.memset.p0i8.i64(i8* align 32 %tmp3, i8 0, i64 32, i1 false)
  call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal512_prefer512(<8 x i64>* %tmp2, <8 x i64>* %tmp)
  %tmp4 = load <8 x i64>, <8 x i64>* %tmp2, align 32
  store <8 x i64> %tmp4, <8 x i64>* %arg, align 2
  ret void
}

; This should not promote
define internal fastcc void @callee_avx512_legal256_prefer256_call_avx512_legal512_prefer256(<8 x i64>* %arg, <8 x i64>* readonly %arg1) #1 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@callee_avx512_legal256_prefer256_call_avx512_legal512_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]], <8 x i64>* readonly [[ARG1:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1]]
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]]
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@callee_avx512_legal256_prefer256_call_avx512_legal512_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[ARG:%.*]], <8 x i64>* noalias nocapture nonnull readonly align 32 dereferenceable(64) [[ARG1:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]], align 32
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = load <8 x i64>, <8 x i64>* %arg1
  store <8 x i64> %tmp, <8 x i64>* %arg
  ret void
}

define void @avx512_legal256_prefer256_call_avx512_legal512_prefer256(<8 x i64>* %arg) #2 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@avx512_legal256_prefer256_call_avx512_legal512_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ARGPROMOTION-NEXT:    call void @llvm.memset.p0i8.i64(i8* align 32 [[TMP3]], i8 0, i64 32, i1 false)
; ARGPROMOTION-NEXT:    call fastcc void @callee_avx512_legal256_prefer256_call_avx512_legal512_prefer256(<8 x i64>* [[TMP2]], <8 x i64>* [[TMP]])
; ARGPROMOTION-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@avx512_legal256_prefer256_call_avx512_legal512_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* nocapture writeonly [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ATTRIBUTOR-NEXT:    call void @llvm.memset.p0i8.i64(i8* nonnull align 32 dereferenceable(64) [[TMP3]], i8 0, i64 32, i1 false)
; ATTRIBUTOR-NEXT:    call fastcc void @callee_avx512_legal256_prefer256_call_avx512_legal512_prefer256(<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[TMP2]], <8 x i64>* noalias nocapture nonnull readonly align 32 dereferenceable(64) [[TMP]])
; ATTRIBUTOR-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = alloca <8 x i64>, align 32
  %tmp2 = alloca <8 x i64>, align 32
  %tmp3 = bitcast <8 x i64>* %tmp to i8*
  call void @llvm.memset.p0i8.i64(i8* align 32 %tmp3, i8 0, i64 32, i1 false)
  call fastcc void @callee_avx512_legal256_prefer256_call_avx512_legal512_prefer256(<8 x i64>* %tmp2, <8 x i64>* %tmp)
  %tmp4 = load <8 x i64>, <8 x i64>* %tmp2, align 32
  store <8 x i64> %tmp4, <8 x i64>* %arg, align 2
  ret void
}

; This should not promote
define internal fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal256_prefer256(<8 x i64>* %arg, <8 x i64>* readonly %arg1) #2 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer256_call_avx512_legal256_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]], <8 x i64>* readonly [[ARG1:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1]]
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]]
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@callee_avx512_legal512_prefer256_call_avx512_legal256_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[ARG:%.*]], <8 x i64>* noalias nocapture nonnull readonly align 32 dereferenceable(64) [[ARG1:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]], align 32
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = load <8 x i64>, <8 x i64>* %arg1
  store <8 x i64> %tmp, <8 x i64>* %arg
  ret void
}

define void @avx512_legal512_prefer256_call_avx512_legal256_prefer256(<8 x i64>* %arg) #1 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@avx512_legal512_prefer256_call_avx512_legal256_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ARGPROMOTION-NEXT:    call void @llvm.memset.p0i8.i64(i8* align 32 [[TMP3]], i8 0, i64 32, i1 false)
; ARGPROMOTION-NEXT:    call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal256_prefer256(<8 x i64>* [[TMP2]], <8 x i64>* [[TMP]])
; ARGPROMOTION-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@avx512_legal512_prefer256_call_avx512_legal256_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* nocapture writeonly [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ATTRIBUTOR-NEXT:    call void @llvm.memset.p0i8.i64(i8* nonnull align 32 dereferenceable(64) [[TMP3]], i8 0, i64 32, i1 false)
; ATTRIBUTOR-NEXT:    call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal256_prefer256(<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[TMP2]], <8 x i64>* noalias nocapture nonnull readonly align 32 dereferenceable(64) [[TMP]])
; ATTRIBUTOR-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = alloca <8 x i64>, align 32
  %tmp2 = alloca <8 x i64>, align 32
  %tmp3 = bitcast <8 x i64>* %tmp to i8*
  call void @llvm.memset.p0i8.i64(i8* align 32 %tmp3, i8 0, i64 32, i1 false)
  call fastcc void @callee_avx512_legal512_prefer256_call_avx512_legal256_prefer256(<8 x i64>* %tmp2, <8 x i64>* %tmp)
  %tmp4 = load <8 x i64>, <8 x i64>* %tmp2, align 32
  store <8 x i64> %tmp4, <8 x i64>* %arg, align 2
  ret void
}

; This should promote
define internal fastcc void @callee_avx2_legal256_prefer256_call_avx2_legal512_prefer256(<8 x i64>* %arg, <8 x i64>* readonly %arg1) #3 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@callee_avx2_legal256_prefer256_call_avx2_legal512_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]], <8 x i64> [[ARG1_VAL:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    store <8 x i64> [[ARG1_VAL]], <8 x i64>* [[ARG]]
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@callee_avx2_legal256_prefer256_call_avx2_legal512_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
<<<<<<< HEAD
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]], align 32
||||||| parent of 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0:%.*]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG:%.*]], align 32
=======
; ATTRIBUTOR-NEXT:    store <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64>* [[ARG]], align 32
>>>>>>> 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = load <8 x i64>, <8 x i64>* %arg1
  store <8 x i64> %tmp, <8 x i64>* %arg
  ret void
}

define void @avx2_legal256_prefer256_call_avx2_legal512_prefer256(<8 x i64>* %arg) #4 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@avx2_legal256_prefer256_call_avx2_legal512_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ARGPROMOTION-NEXT:    call void @llvm.memset.p0i8.i64(i8* align 32 [[TMP3]], i8 0, i64 32, i1 false)
; ARGPROMOTION-NEXT:    [[TMP_VAL:%.*]] = load <8 x i64>, <8 x i64>* [[TMP]]
; ARGPROMOTION-NEXT:    call fastcc void @callee_avx2_legal256_prefer256_call_avx2_legal512_prefer256(<8 x i64>* [[TMP2]], <8 x i64> [[TMP_VAL]])
; ARGPROMOTION-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@avx2_legal256_prefer256_call_avx2_legal512_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* nocapture writeonly [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP_0_VECBLEND:%.*]] = select <8 x i1> <i1 true, i1 true, i1 true, i1 true, i1 false, i1 false, i1 false, i1 false>, <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64> undef
; ATTRIBUTOR-NEXT:    call fastcc void @callee_avx2_legal256_prefer256_call_avx2_legal512_prefer256(<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[TMP2]])
; ATTRIBUTOR-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = alloca <8 x i64>, align 32
  %tmp2 = alloca <8 x i64>, align 32
  %tmp3 = bitcast <8 x i64>* %tmp to i8*
  call void @llvm.memset.p0i8.i64(i8* align 32 %tmp3, i8 0, i64 32, i1 false)
  call fastcc void @callee_avx2_legal256_prefer256_call_avx2_legal512_prefer256(<8 x i64>* %tmp2, <8 x i64>* %tmp)
  %tmp4 = load <8 x i64>, <8 x i64>* %tmp2, align 32
  store <8 x i64> %tmp4, <8 x i64>* %arg, align 2
  ret void
}

; This should promote
define internal fastcc void @callee_avx2_legal512_prefer256_call_avx2_legal256_prefer256(<8 x i64>* %arg, <8 x i64>* readonly %arg1) #4 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@callee_avx2_legal512_prefer256_call_avx2_legal256_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]], <8 x i64> [[ARG1_VAL:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    store <8 x i64> [[ARG1_VAL]], <8 x i64>* [[ARG]]
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@callee_avx2_legal512_prefer256_call_avx2_legal256_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
<<<<<<< HEAD
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG]], align 32
||||||| parent of 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    [[ARG1_PRIV:%.*]] = alloca <8 x i64>
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP0:%.*]], <8 x i64>* [[ARG1_PRIV]]
; ATTRIBUTOR-NEXT:    [[TMP:%.*]] = load <8 x i64>, <8 x i64>* [[ARG1_PRIV]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP]], <8 x i64>* [[ARG:%.*]], align 32
=======
; ATTRIBUTOR-NEXT:    store <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64>* [[ARG]], align 32
>>>>>>> 2bf5733254a... FIXES FIXES FIXES
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = load <8 x i64>, <8 x i64>* %arg1
  store <8 x i64> %tmp, <8 x i64>* %arg
  ret void
}

define void @avx2_legal512_prefer256_call_avx2_legal256_prefer256(<8 x i64>* %arg) #3 {
; ARGPROMOTION-LABEL: define {{[^@]+}}@avx2_legal512_prefer256_call_avx2_legal256_prefer256
; ARGPROMOTION-SAME: (<8 x i64>* [[ARG:%.*]])
; ARGPROMOTION-NEXT:  bb:
; ARGPROMOTION-NEXT:    [[TMP:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ARGPROMOTION-NEXT:    [[TMP3:%.*]] = bitcast <8 x i64>* [[TMP]] to i8*
; ARGPROMOTION-NEXT:    call void @llvm.memset.p0i8.i64(i8* align 32 [[TMP3]], i8 0, i64 32, i1 false)
; ARGPROMOTION-NEXT:    [[TMP_VAL:%.*]] = load <8 x i64>, <8 x i64>* [[TMP]]
; ARGPROMOTION-NEXT:    call fastcc void @callee_avx2_legal512_prefer256_call_avx2_legal256_prefer256(<8 x i64>* [[TMP2]], <8 x i64> [[TMP_VAL]])
; ARGPROMOTION-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ARGPROMOTION-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ARGPROMOTION-NEXT:    ret void
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@avx2_legal512_prefer256_call_avx2_legal256_prefer256
; ATTRIBUTOR-SAME: (<8 x i64>* nocapture writeonly [[ARG:%.*]])
; ATTRIBUTOR-NEXT:  bb:
; ATTRIBUTOR-NEXT:    [[TMP2:%.*]] = alloca <8 x i64>, align 32
; ATTRIBUTOR-NEXT:    [[TMP_0_VECBLEND:%.*]] = select <8 x i1> <i1 true, i1 true, i1 true, i1 true, i1 false, i1 false, i1 false, i1 false>, <8 x i64> <i64 0, i64 0, i64 0, i64 0, i64 undef, i64 undef, i64 undef, i64 undef>, <8 x i64> undef
; ATTRIBUTOR-NEXT:    call fastcc void @callee_avx2_legal512_prefer256_call_avx2_legal256_prefer256(<8 x i64>* noalias nocapture nonnull writeonly align 32 dereferenceable(64) [[TMP2]])
; ATTRIBUTOR-NEXT:    [[TMP4:%.*]] = load <8 x i64>, <8 x i64>* [[TMP2]], align 32
; ATTRIBUTOR-NEXT:    store <8 x i64> [[TMP4]], <8 x i64>* [[ARG]], align 2
; ATTRIBUTOR-NEXT:    ret void
;
bb:
  %tmp = alloca <8 x i64>, align 32
  %tmp2 = alloca <8 x i64>, align 32
  %tmp3 = bitcast <8 x i64>* %tmp to i8*
  call void @llvm.memset.p0i8.i64(i8* align 32 %tmp3, i8 0, i64 32, i1 false)
  call fastcc void @callee_avx2_legal512_prefer256_call_avx2_legal256_prefer256(<8 x i64>* %tmp2, <8 x i64>* %tmp)
  %tmp4 = load <8 x i64>, <8 x i64>* %tmp2, align 32
  store <8 x i64> %tmp4, <8 x i64>* %arg, align 2
  ret void
}

; Function Attrs: argmemonly nounwind
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1) #5

attributes #0 = { inlinehint norecurse nounwind uwtable "target-features"="+avx512vl" "min-legal-vector-width"="512" "prefer-vector-width"="512" }
attributes #1 = { inlinehint norecurse nounwind uwtable "target-features"="+avx512vl" "min-legal-vector-width"="512" "prefer-vector-width"="256" }
attributes #2 = { inlinehint norecurse nounwind uwtable "target-features"="+avx512vl" "min-legal-vector-width"="256" "prefer-vector-width"="256" }
attributes #3 = { inlinehint norecurse nounwind uwtable "target-features"="+avx2" "min-legal-vector-width"="512" "prefer-vector-width"="256" }
attributes #4 = { inlinehint norecurse nounwind uwtable "target-features"="+avx2" "min-legal-vector-width"="256" "prefer-vector-width"="256" }
attributes #5 = { argmemonly nounwind }
