; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-attributes
; RUN: opt -attributor -enable-new-pm=0 -attributor-manifest-internal -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=3 -S < %s | FileCheck %s --check-prefixes=CHECK,CHECK_NO_MBEC,NOT_CGSCC_NPM_NO_MBEC,NOT_CGSCC_OPM_NO_MBEC,NOT_TUNIT_NPM_NO_MBEC,IS__TUNIT_____NO_MBEC,IS________OPM_NO_MBEC,IS__TUNIT_OPM_NO_MBEC
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=3 -S < %s | FileCheck %s --check-prefixes=CHECK,CHECK_NO_MBEC,NOT_CGSCC_OPM_NO_MBEC,NOT_CGSCC_NPM_NO_MBEC,NOT_TUNIT_OPM_NO_MBEC,IS__TUNIT_____NO_MBEC,IS________NPM_NO_MBEC,IS__TUNIT_NPM_NO_MBEC
; RUN: opt -attributor-cgscc -enable-new-pm=0 -attributor-manifest-internal -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,CHECK_NO_MBEC,NOT_TUNIT_NPM_NO_MBEC,NOT_TUNIT_OPM_NO_MBEC,NOT_CGSCC_NPM_NO_MBEC,IS__CGSCC_____NO_MBEC,IS________OPM_NO_MBEC,IS__CGSCC_OPM_NO_MBEC
; RUN: opt -aa-pipeline=basic-aa -passes=attributor-cgscc -attributor-manifest-internal -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,CHECK_NO_MBEC,NOT_TUNIT_NPM_NO_MBEC,NOT_TUNIT_OPM_NO_MBEC,NOT_CGSCC_OPM_NO_MBEC,IS__CGSCC_____NO_MBEC,IS________NPM_NO_MBEC,IS__CGSCC_NPM_NO_MBEC
;
; RUN: opt -attributor -enable-new-pm=0 -attributor-manifest-internal -attributor-use-must-be-executed-context  -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=3 -S < %s | FileCheck %s --check-prefixes=CHECK,CHECK_MBEC,NOT_CGSCC_NPM_MBEC,NOT_CGSCC_OPM_MBEC,NOT_TUNIT_NPM_MBEC,IS__TUNIT_____MBEC,IS________OPM_MBEC,IS__TUNIT_OPM_MBEC
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -attributor-use-must-be-executed-context  -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=3 -S < %s | FileCheck %s --check-prefixes=CHECK,CHECK_MBEC,NOT_CGSCC_OPM_MBEC,NOT_CGSCC_NPM_MBEC,NOT_TUNIT_OPM_MBEC,IS__TUNIT_____MBEC,IS________NPM_MBEC,IS__TUNIT_NPM_MBEC
; RUN: opt -attributor-cgscc -enable-new-pm=0 -attributor-manifest-internal -attributor-use-must-be-executed-context  -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,CHECK_MBEC,NOT_TUNIT_NPM_MBEC,NOT_TUNIT_OPM_MBEC,NOT_CGSCC_NPM_MBEC,IS__CGSCC_____MBEC,IS________OPM_MBEC,IS__CGSCC_OPM_MBEC
; RUN: opt -aa-pipeline=basic-aa -passes=attributor-cgscc -attributor-manifest-internal -attributor-use-must-be-executed-context  -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,CHECK_MBEC,NOT_TUNIT_NPM_MBEC,NOT_TUNIT_OPM_MBEC,NOT_CGSCC_OPM_MBEC,IS__CGSCC_____MBEC,IS________NPM_MBEC,IS__CGSCC_NPM_MBEC
;
; Mostly check we do not crash on these uses

define internal void @internal(void (i8*)* %fp) {
;
;
; CHECK_NO_MBEC-LABEL: define {{[^@]+}}@internal
; CHECK_NO_MBEC-SAME: (void (i8*)* [[FP:%.*]]) {
; CHECK_NO_MBEC-NEXT:  entry:
; CHECK_NO_MBEC-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK_NO_MBEC-NEXT:    call void @foo(i32* noalias nocapture nofree noundef nonnull writeonly align 4 dereferenceable(4) [[A]]) [[ATTR1:#.*]]
; CHECK_NO_MBEC-NEXT:    call void [[FP]](i8* bitcast (void (i32*)* @foo to i8*))
; CHECK_NO_MBEC-NEXT:    call void @callback1(void (i32*)* noundef nonnull @foo)
; CHECK_NO_MBEC-NEXT:    call void @callback2(void (i8*)* noundef bitcast (void (i32*)* @foo to void (i8*)*))
; CHECK_NO_MBEC-NEXT:    call void @callback2(void (i8*)* [[FP]])
; CHECK_NO_MBEC-NEXT:    [[TMP1:%.*]] = bitcast i32* [[A]] to i8*
; CHECK_NO_MBEC-NEXT:    call void [[FP]](i8* [[TMP1]])
; CHECK_NO_MBEC-NEXT:    ret void
;
; CHECK_MBEC-LABEL: define {{[^@]+}}@internal
; CHECK_MBEC-SAME: (void (i8*)* nonnull [[FP:%.*]]) {
; CHECK_MBEC-NEXT:  entry:
; CHECK_MBEC-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK_MBEC-NEXT:    call void @foo(i32* noalias nocapture nofree noundef nonnull writeonly align 4 dereferenceable(4) [[A]]) [[ATTR1:#.*]]
; CHECK_MBEC-NEXT:    call void [[FP]](i8* bitcast (void (i32*)* @foo to i8*))
; CHECK_MBEC-NEXT:    call void @callback1(void (i32*)* noundef nonnull @foo)
; CHECK_MBEC-NEXT:    call void @callback2(void (i8*)* noundef bitcast (void (i32*)* @foo to void (i8*)*))
; CHECK_MBEC-NEXT:    call void @callback2(void (i8*)* nonnull [[FP]])
; CHECK_MBEC-NEXT:    [[TMP1:%.*]] = bitcast i32* [[A]] to i8*
; CHECK_MBEC-NEXT:    call void [[FP]](i8* [[TMP1]])
; CHECK_MBEC-NEXT:    ret void
;
entry:
  %a = alloca i32, align 4
  %tmp = bitcast i32* %a to i8*
  call void @foo(i32* nonnull %a)
  call void %fp(i8* bitcast (void (i32*)* @foo to i8*))
  call void @callback1(void (i32*)* nonnull @foo)
  call void @callback2(void (i8*)* bitcast (void (i32*)* @foo to void (i8*)*))
  call void @callback2(void (i8*)* %fp)
  %tmp1 = bitcast i32* %a to i8*
  call void %fp(i8* %tmp1)
  ret void
}

define void @external(void (i8*)* %fp) {
;
;
; CHECK_NO_MBEC-LABEL: define {{[^@]+}}@external
; CHECK_NO_MBEC-SAME: (void (i8*)* [[FP:%.*]]) {
; CHECK_NO_MBEC-NEXT:  entry:
; CHECK_NO_MBEC-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK_NO_MBEC-NEXT:    call void @foo(i32* noalias nocapture nofree noundef nonnull writeonly align 4 dereferenceable(4) [[A]]) [[ATTR1]]
; CHECK_NO_MBEC-NEXT:    call void @callback1(void (i32*)* noundef nonnull @foo)
; CHECK_NO_MBEC-NEXT:    call void @callback2(void (i8*)* noundef bitcast (void (i32*)* @foo to void (i8*)*))
; CHECK_NO_MBEC-NEXT:    call void @callback2(void (i8*)* [[FP]])
; CHECK_NO_MBEC-NEXT:    call void [[FP]](i8* bitcast (void (i32*)* @foo to i8*))
; CHECK_NO_MBEC-NEXT:    [[TMP1:%.*]] = bitcast i32* [[A]] to i8*
; CHECK_NO_MBEC-NEXT:    call void [[FP]](i8* [[TMP1]])
; CHECK_NO_MBEC-NEXT:    call void @internal(void (i8*)* [[FP]])
; CHECK_NO_MBEC-NEXT:    ret void
;
; CHECK_MBEC-LABEL: define {{[^@]+}}@external
; CHECK_MBEC-SAME: (void (i8*)* [[FP:%.*]]) {
; CHECK_MBEC-NEXT:  entry:
; CHECK_MBEC-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK_MBEC-NEXT:    call void @foo(i32* noalias nocapture nofree noundef nonnull writeonly align 4 dereferenceable(4) [[A]]) [[ATTR1]]
; CHECK_MBEC-NEXT:    call void @callback1(void (i32*)* noundef nonnull @foo)
; CHECK_MBEC-NEXT:    call void @callback2(void (i8*)* noundef bitcast (void (i32*)* @foo to void (i8*)*))
; CHECK_MBEC-NEXT:    call void @callback2(void (i8*)* [[FP]])
; CHECK_MBEC-NEXT:    call void [[FP]](i8* bitcast (void (i32*)* @foo to i8*))
; CHECK_MBEC-NEXT:    [[TMP1:%.*]] = bitcast i32* [[A]] to i8*
; CHECK_MBEC-NEXT:    call void [[FP]](i8* [[TMP1]])
; CHECK_MBEC-NEXT:    call void @internal(void (i8*)* nonnull [[FP]])
; CHECK_MBEC-NEXT:    ret void
;
entry:
  %a = alloca i32, align 4
  %tmp = bitcast i32* %a to i8*
  call void @foo(i32* nonnull %a)
  call void @callback1(void (i32*)* nonnull @foo)
  call void @callback2(void (i8*)* bitcast (void (i32*)* @foo to void (i8*)*))
  call void @callback2(void (i8*)* %fp)
  call void %fp(i8* bitcast (void (i32*)* @foo to i8*))
  %tmp1 = bitcast i32* %a to i8*
  call void %fp(i8* %tmp1)
  call void @internal(void (i8*)* %fp)
  ret void
}

define internal void @foo(i32* %a) {
; IS__TUNIT_____NO_MBEC: Function Attrs: argmemonly nofree nosync nounwind willreturn writeonly
; IS__TUNIT_____NO_MBEC-LABEL: define {{[^@]+}}@foo
; IS__TUNIT_____NO_MBEC-SAME: (i32* nocapture nofree writeonly [[A:%.*]]) [[ATTR0:#.*]] {
; IS__TUNIT_____NO_MBEC-NEXT:  entry:
; IS__TUNIT_____NO_MBEC-NEXT:    store i32 0, i32* [[A]], align 4
; IS__TUNIT_____NO_MBEC-NEXT:    ret void
;
; IS__CGSCC_____NO_MBEC: Function Attrs: argmemonly nofree norecurse nosync nounwind willreturn writeonly
; IS__CGSCC_____NO_MBEC-LABEL: define {{[^@]+}}@foo
; IS__CGSCC_____NO_MBEC-SAME: (i32* nocapture nofree writeonly [[A:%.*]]) [[ATTR0:#.*]] {
; IS__CGSCC_____NO_MBEC-NEXT:  entry:
; IS__CGSCC_____NO_MBEC-NEXT:    store i32 0, i32* [[A]], align 4
; IS__CGSCC_____NO_MBEC-NEXT:    ret void
;
; IS__TUNIT_____MBEC: Function Attrs: argmemonly nofree nosync nounwind willreturn writeonly
; IS__TUNIT_____MBEC-LABEL: define {{[^@]+}}@foo
; IS__TUNIT_____MBEC-SAME: (i32* nocapture nofree nonnull writeonly align 4 dereferenceable(4) [[A:%.*]]) [[ATTR0:#.*]] {
; IS__TUNIT_____MBEC-NEXT:  entry:
; IS__TUNIT_____MBEC-NEXT:    store i32 0, i32* [[A]], align 4
; IS__TUNIT_____MBEC-NEXT:    ret void
;
; IS__CGSCC_____MBEC: Function Attrs: argmemonly nofree norecurse nosync nounwind willreturn writeonly
; IS__CGSCC_____MBEC-LABEL: define {{[^@]+}}@foo
; IS__CGSCC_____MBEC-SAME: (i32* nocapture nofree nonnull writeonly align 4 dereferenceable(4) [[A:%.*]]) [[ATTR0:#.*]] {
; IS__CGSCC_____MBEC-NEXT:  entry:
; IS__CGSCC_____MBEC-NEXT:    store i32 0, i32* [[A]], align 4
; IS__CGSCC_____MBEC-NEXT:    ret void
;
entry:
  store i32 0, i32* %a
  ret void
}

declare void @callback1(void (i32*)*)
declare void @callback2(void (i8*)*)

