; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-attributes
; RUN: opt -attributor -enable-new-pm=0 -attributor-manifest-internal  -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=2 -S < %s | FileCheck %s --check-prefixes=CHECK,NOT_CGSCC_NPM,NOT_CGSCC_OPM,NOT_TUNIT_NPM,IS__TUNIT____,IS________OPM,IS__TUNIT_OPM
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal  -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=2 -S < %s | FileCheck %s --check-prefixes=CHECK,NOT_CGSCC_OPM,NOT_CGSCC_NPM,NOT_TUNIT_OPM,IS__TUNIT____,IS________NPM,IS__TUNIT_NPM
; RUN: opt -attributor-cgscc -enable-new-pm=0 -attributor-manifest-internal  -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,NOT_TUNIT_NPM,NOT_TUNIT_OPM,NOT_CGSCC_NPM,IS__CGSCC____,IS________OPM,IS__CGSCC_OPM
; RUN: opt -aa-pipeline=basic-aa -passes=attributor-cgscc -attributor-manifest-internal  -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,NOT_TUNIT_NPM,NOT_TUNIT_OPM,NOT_CGSCC_OPM,IS__CGSCC____,IS________NPM,IS__CGSCC_NPM

target datalayout = "e-m:e-i54:64-f80:128-n8:16:32:64-S128"

declare void @sink() nounwind willreturn nosync nofree

define internal void @callee(i1 %a) {
; CHECK: Function Attrs: nofree nosync nounwind mustprogress
; CHECK-LABEL: define {{[^@]+}}@callee
; CHECK-SAME: (i1 [[A:%.*]]) [[ATTR1:#.*]] {
; CHECK-NEXT:    call void @sink() [[ATTR2:#.*]]
; CHECK-NEXT:    br i1 [[A]], label [[T:%.*]], label [[F:%.*]]
; CHECK:       t:
; CHECK-NEXT:    call void @callee(i1 noundef false) [[ATTR1]]
; CHECK-NEXT:    br label [[F]]
; CHECK:       f:
; CHECK-NEXT:    ret void
;
  call void @sink()
  br i1 %a, label %t, label %f
t:
  call void @callee(i1 false)
  br label %f
f:
  ret void
}

define void @caller(i1 %a) mustprogress {
; IS__TUNIT____: Function Attrs: nofree nosync nounwind mustprogress
; IS__TUNIT____-LABEL: define {{[^@]+}}@caller
; IS__TUNIT____-SAME: (i1 [[A:%.*]]) [[ATTR1:#.*]] {
; IS__TUNIT____-NEXT:    call void @callee(i1 [[A]]) [[ATTR1]]
; IS__TUNIT____-NEXT:    ret void
;
; IS__CGSCC____: Function Attrs: nofree nosync nounwind mustprogress
; IS__CGSCC____-LABEL: define {{[^@]+}}@caller
; IS__CGSCC____-SAME: (i1 [[A:%.*]]) [[ATTR1:#.*]] {
; IS__CGSCC____-NEXT:    call void @callee(i1 [[A]]) [[ATTR3:#.*]]
; IS__CGSCC____-NEXT:    ret void
;
  call void @callee(i1 %a)
  ret void
}
