; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-file=%S/call_config.json -S | FileCheck %s

target datalayout = "e-m:e-Fn32-i64:64-i128:128-n32:64-S128-v256:256:256-v512:512:512"

@stderr = external global ptr, align 8
@.str = private unnamed_addr constant [23 x i8] c"integer %d, double %f\0A\00", align 1

; Function Attrs: noinline nounwind optnone uwtable
define dso_local signext i32 @bar() {
; CHECK-LABEL: define dso_local signext i32 @bar() {
; CHECK-NEXT:    ret i32 0
;
  ret i32 0
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local signext i32 @foo(i32 noundef signext %0, double noundef %1) {
; CHECK-LABEL: define dso_local signext i32 @foo(
; CHECK-SAME: i32 noundef signext [[TMP0:%.*]], double noundef [[TMP1:%.*]]) {
; CHECK-NEXT:    [[TMP3:%.*]] = alloca <{ i32, i32, ptr, i32, i32, ptr, i32, i32, [4 x i8], i32, i32, i32, double }>, align 8
; CHECK-NEXT:    [[TMP4:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[TMP5:%.*]] = alloca double, align 8
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP4]], align 4
; CHECK-NEXT:    store double [[TMP1]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr @stderr, align 8
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = load double, ptr [[TMP5]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP3]], ptr @__instrumentor_value_pack, i64 64, i1 false)
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw <{ i32, i32, ptr, i32, i32, ptr, i32, i32, [4 x i8], i32, i32, i32, double }>, ptr [[TMP3]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP6]], ptr [[TMP9]], align 8
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw <{ i32, i32, ptr, i32, i32, ptr, i32, i32, [4 x i8], i32, i32, i32, double }>, ptr [[TMP3]], i32 0, i32 9
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[TMP10]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw <{ i32, i32, ptr, i32, i32, ptr, i32, i32, [4 x i8], i32, i32, i32, double }>, ptr [[TMP3]], i32 0, i32 12
; CHECK-NEXT:    store double [[TMP8]], ptr [[TMP11]], align 8
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @fprintf, ptr @__instrumentor_.str, i64 0, ptr null, i32 4, ptr [[TMP3]], i8 0) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i8, ptr [[TMP3]], i32 8
; CHECK-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP12]], align 8
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i8, ptr [[TMP3]], i32 24
; CHECK-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[TMP14]], align 8
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i8, ptr [[TMP3]], i32 44
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[TMP16]], align 4
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i8, ptr [[TMP3]], i32 56
; CHECK-NEXT:    [[TMP19:%.*]] = load double, ptr [[TMP18]], align 8
; CHECK-NEXT:    [[TMP20:%.*]] = call signext i32 (ptr, ptr, ...) @fprintf(ptr noundef [[TMP13]], ptr noundef [[TMP15]], i32 noundef signext [[TMP17]], double noundef [[TMP19]])
; CHECK-NEXT:    [[TMP21:%.*]] = zext i32 [[TMP20]] to i64
; CHECK-NEXT:    [[TMP22:%.*]] = call i64 @__instrumentor_post_call(ptr @fprintf, ptr @__instrumentor_.str, i64 0, ptr null, i64 [[TMP21]], i32 4, i32 4, ptr [[TMP3]], i8 0) #[[ATTR1]]
; CHECK-NEXT:    [[TMP23:%.*]] = trunc i64 [[TMP22]] to i32
; CHECK-NEXT:    ret i32 [[TMP23]]
;
  %3 = alloca i32, align 4
  %4 = alloca double, align 8
  store i32 %0, ptr %3, align 4
  store double %1, ptr %4, align 8
  %5 = load ptr, ptr @stderr, align 8
  %6 = load i32, ptr %3, align 4
  %7 = load double, ptr %4, align 8
  %8 = call signext i32 (ptr, ptr, ...) @fprintf(ptr noundef %5, ptr noundef @.str, i32 noundef signext %6, double noundef %7) #2
  ret i32 %8
}

; Function Attrs: nounwind
declare signext i32 @fprintf(ptr noundef, ptr noundef, ...)

; Function Attrs: noinline nounwind optnone uwtable
define dso_local signext i32 @func() {
; CHECK-LABEL: define dso_local signext i32 @func() {
; CHECK-NEXT:    [[TMP1:%.*]] = alloca <{ i32, i32, [4 x i8], i32, i32, i32, double }>, align 8
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @bar, ptr @__instrumentor_.str.1, i64 0, ptr null, i32 0, ptr null, i8 1) #[[ATTR1]]
; CHECK-NEXT:    [[TMP2:%.*]] = call signext i32 @bar()
; CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @__instrumentor_post_call(ptr @bar, ptr @__instrumentor_.str.1, i64 0, ptr null, i64 [[TMP3]], i32 4, i32 0, ptr null, i8 1) #[[ATTR1]]
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i32
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP1]], ptr @__instrumentor_value_pack.3, i64 32, i1 false)
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32, i32, i32, double }>, ptr [[TMP1]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP6]], align 4
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @foo, ptr @__instrumentor_.str.2, i64 0, ptr null, i32 2, ptr [[TMP1]], i8 1) #[[ATTR1]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i32 12
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i32 24
; CHECK-NEXT:    [[TMP10:%.*]] = load double, ptr [[TMP9]], align 8
; CHECK-NEXT:    [[TMP11:%.*]] = call signext i32 @foo(i32 noundef signext [[TMP8]], double noundef [[TMP10]])
; CHECK-NEXT:    [[TMP12:%.*]] = zext i32 [[TMP11]] to i64
; CHECK-NEXT:    [[TMP13:%.*]] = call i64 @__instrumentor_post_call(ptr @foo, ptr @__instrumentor_.str.2, i64 0, ptr null, i64 [[TMP12]], i32 4, i32 2, ptr [[TMP1]], i8 1) #[[ATTR1]]
; CHECK-NEXT:    [[TMP14:%.*]] = trunc i64 [[TMP13]] to i32
; CHECK-NEXT:    ret i32 [[TMP14]]
;
  %1 = call signext i32 @bar()
  %2 = call signext i32 @foo(i32 noundef signext %1, double noundef 1.000000e+01)
  ret i32 %2
}
