; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-file=%S/function_config.json -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

@A = dso_local global i32 0, align 4

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main() #0 {
; CHECK-LABEL: define dso_local i32 @main() {
; CHECK-NEXT:    call void @__instrumentor_pre_function(ptr @main, ptr @__instrumentor_.str, i32 0, ptr null, i8 1) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr @A, align 4
; CHECK-NEXT:    call void @__instrumentor_post_function(ptr @main, ptr @__instrumentor_.str, i32 0, ptr null, i8 1) #[[ATTR1]]
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %1 = load i32, ptr @A, align 4
  ret i32 %1
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @notmain1() #0 {
; CHECK-LABEL: define dso_local i32 @notmain1() {
; CHECK-NEXT:    call void @__instrumentor_pre_function(ptr @notmain1, ptr @__instrumentor_.str.1, i32 0, ptr null, i8 0) #[[ATTR1]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr @A, align 4
; CHECK-NEXT:    call void @__instrumentor_post_function(ptr @notmain1, ptr @__instrumentor_.str.1, i32 0, ptr null, i8 0) #[[ATTR1]]
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %1 = load i32, ptr @A, align 4
  ret i32 %1
}

define dso_local i32 @notmain2(i32 %0, ptr %1) #0 {
; CHECK-LABEL: define dso_local i32 @notmain2(
; CHECK-SAME: i32 [[TMP0:%.*]], ptr [[TMP1:%.*]]) {
; CHECK-NEXT:    [[TMP3:%.*]] = alloca <{ i32, i32, [4 x i8], i32, i32, i32, ptr }>, align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP3]], ptr @__instrumentor_value_pack, i64 32, i1 false)
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32, i32, i32, ptr }>, ptr [[TMP3]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32, i32, i32, ptr }>, ptr [[TMP3]], i32 0, i32 6
; CHECK-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
; CHECK-NEXT:    call void @__instrumentor_pre_function(ptr @notmain2, ptr @__instrumentor_.str.2, i32 2, ptr [[TMP3]], i8 0) #[[ATTR1]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i8, ptr [[TMP3]], i32 12
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i8, ptr [[TMP3]], i32 24
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP3]], ptr @__instrumentor_value_pack, i64 32, i1 false)
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32, i32, i32, ptr }>, ptr [[TMP3]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP10]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32, i32, i32, ptr }>, ptr [[TMP3]], i32 0, i32 6
; CHECK-NEXT:    store ptr [[TMP1]], ptr [[TMP11]], align 8
; CHECK-NEXT:    call void @__instrumentor_post_function(ptr @notmain2, ptr @__instrumentor_.str.2, i32 2, ptr [[TMP3]], i8 0) #[[ATTR1]]
; CHECK-NEXT:    ret i32 0
;
  ret i32 0
}
