; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --include-generated-funcs --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-file=%S/global_config.json -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

@A1 = dso_local global i32 1, align 4
@A2 = dso_local constant i32 2, align 4
@A3 = internal global i32 3, align 4
@A4 = internal constant i32 4, align 4
@A5 = external global i32, align 4
@A6 = external constant i32, align 4
@B1 = dso_local global ptr null, align 8
@B2 = dso_local constant ptr null, align 8
@B3 = internal global ptr null, align 8
@B4 = internal constant ptr null, align 8
@B5 = external global ptr, align 8
@B6 = external constant ptr, align 8
@C1 = dso_local global [100 x i32] zeroinitializer, align 16
@C2 = dso_local constant [100 x i32] zeroinitializer, align 16
@C3 = internal global [100 x i32] zeroinitializer, align 16
@C4 = internal constant [100 x i32] zeroinitializer, align 16
@C5 = external global [100 x i32], align 16
@C6 = external constant [100 x i32], align 16
@D1 = dso_local global x86_fp80 0xK00000000000000000000, align 16
@D2 = dso_local constant x86_fp80 0xK00000000000000000000, align 16
@D3 = internal global x86_fp80 0xK00000000000000000000, align 16
@D4 = internal constant x86_fp80 0xK00000000000000000000, align 16
@D5 = external global x86_fp80, align 16
@D6 = external global x86_fp80, align 16

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 2}
!5 = !{!"clang version 21.0.0git (https://github.com/jdoerfert/llvm-project.git 1ccefa476b21fceb24068bd85db34b822c51f606)"}
;.
; CHECK: @__instrumentor_shadow.A1 = global ptr poison
; CHECK: @A1 = dso_local global i32 1, align 4
; CHECK: @__instrumentor_shadow.A2 = global ptr poison
; CHECK: @A2 = dso_local constant i32 2, align 4
; CHECK: @__instrumentor_shadow.A3 = internal global ptr poison
; CHECK: @A3 = internal global i32 3, align 4
; CHECK: @__instrumentor_shadow.A4 = internal global ptr poison
; CHECK: @A4 = internal constant i32 4, align 4
; CHECK: @__instrumentor_shadow.A5 = weak_odr global ptr @A5
; CHECK: @A5 = external global i32, align 4
; CHECK: @__instrumentor_shadow.A6 = weak_odr global ptr @A6
; CHECK: @A6 = external constant i32, align 4
; CHECK: @__instrumentor_shadow.B1 = global ptr poison
; CHECK: @B1 = dso_local global ptr null, align 8
; CHECK: @__instrumentor_shadow.B2 = global ptr poison
; CHECK: @B2 = dso_local constant ptr null, align 8
; CHECK: @__instrumentor_shadow.B3 = internal global ptr poison
; CHECK: @B3 = internal global ptr null, align 8
; CHECK: @__instrumentor_shadow.B4 = internal global ptr poison
; CHECK: @B4 = internal constant ptr null, align 8
; CHECK: @__instrumentor_shadow.B5 = weak_odr global ptr @B5
; CHECK: @B5 = external global ptr, align 8
; CHECK: @__instrumentor_shadow.B6 = weak_odr global ptr @B6
; CHECK: @B6 = external constant ptr, align 8
; CHECK: @__instrumentor_shadow.C1 = global ptr poison
; CHECK: @C1 = dso_local global [100 x i32] zeroinitializer, align 16
; CHECK: @__instrumentor_shadow.C2 = global ptr poison
; CHECK: @C2 = dso_local constant [100 x i32] zeroinitializer, align 16
; CHECK: @__instrumentor_shadow.C3 = internal global ptr poison
; CHECK: @C3 = internal global [100 x i32] zeroinitializer, align 16
; CHECK: @__instrumentor_shadow.C4 = internal global ptr poison
; CHECK: @C4 = internal constant [100 x i32] zeroinitializer, align 16
; CHECK: @__instrumentor_shadow.C5 = weak_odr global ptr @C5
; CHECK: @C5 = external global [100 x i32], align 16
; CHECK: @__instrumentor_shadow.C6 = weak_odr global ptr @C6
; CHECK: @C6 = external constant [100 x i32], align 16
; CHECK: @__instrumentor_shadow.D1 = global ptr poison
; CHECK: @D1 = dso_local global x86_fp80 0xK00000000000000000000, align 16
; CHECK: @__instrumentor_shadow.D2 = global ptr poison
; CHECK: @D2 = dso_local constant x86_fp80 0xK00000000000000000000, align 16
; CHECK: @__instrumentor_shadow.D3 = internal global ptr poison
; CHECK: @D3 = internal global x86_fp80 0xK00000000000000000000, align 16
; CHECK: @__instrumentor_shadow.D4 = internal global ptr poison
; CHECK: @D4 = internal constant x86_fp80 0xK00000000000000000000, align 16
; CHECK: @__instrumentor_shadow.D5 = weak_odr global ptr @D5
; CHECK: @D5 = external global x86_fp80, align 16
; CHECK: @__instrumentor_shadow.D6 = weak_odr global ptr @D6
; CHECK: @D6 = external global x86_fp80, align 16
; CHECK: @llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 1000, ptr @__instrumentor_ctor, ptr null }]
; CHECK: @__instrumentor_.str = private unnamed_addr constant [3 x i8] c"A1\00", align 1
; CHECK: @__instrumentor_.str.1 = private unnamed_addr constant [3 x i8] c"A2\00", align 1
; CHECK: @__instrumentor_.str.2 = private unnamed_addr constant [3 x i8] c"A3\00", align 1
; CHECK: @__instrumentor_.str.3 = private unnamed_addr constant [3 x i8] c"A4\00", align 1
; CHECK: @__instrumentor_.str.4 = private unnamed_addr constant [3 x i8] c"A5\00", align 1
; CHECK: @__instrumentor_.str.5 = private unnamed_addr constant [3 x i8] c"A6\00", align 1
; CHECK: @__instrumentor_.str.6 = private unnamed_addr constant [3 x i8] c"B1\00", align 1
; CHECK: @__instrumentor_.str.7 = private unnamed_addr constant [3 x i8] c"B2\00", align 1
; CHECK: @__instrumentor_.str.8 = private unnamed_addr constant [3 x i8] c"B3\00", align 1
; CHECK: @__instrumentor_.str.9 = private unnamed_addr constant [3 x i8] c"B4\00", align 1
; CHECK: @__instrumentor_.str.10 = private unnamed_addr constant [3 x i8] c"B5\00", align 1
; CHECK: @__instrumentor_.str.11 = private unnamed_addr constant [3 x i8] c"B6\00", align 1
; CHECK: @__instrumentor_.str.12 = private unnamed_addr constant [3 x i8] c"C1\00", align 1
; CHECK: @__instrumentor_.str.13 = private unnamed_addr constant [3 x i8] c"C2\00", align 1
; CHECK: @__instrumentor_.str.14 = private unnamed_addr constant [3 x i8] c"C3\00", align 1
; CHECK: @__instrumentor_.str.15 = private unnamed_addr constant [3 x i8] c"C4\00", align 1
; CHECK: @__instrumentor_.str.16 = private unnamed_addr constant [3 x i8] c"C5\00", align 1
; CHECK: @__instrumentor_.str.17 = private unnamed_addr constant [3 x i8] c"C6\00", align 1
; CHECK: @__instrumentor_.str.18 = private unnamed_addr constant [3 x i8] c"D1\00", align 1
; CHECK: @__instrumentor_.str.19 = private unnamed_addr constant [3 x i8] c"D2\00", align 1
; CHECK: @__instrumentor_.str.20 = private unnamed_addr constant [3 x i8] c"D3\00", align 1
; CHECK: @__instrumentor_.str.21 = private unnamed_addr constant [3 x i8] c"D4\00", align 1
; CHECK: @__instrumentor_.str.22 = private unnamed_addr constant [3 x i8] c"D5\00", align 1
; CHECK: @__instrumentor_.str.23 = private unnamed_addr constant [3 x i8] c"D6\00", align 1
;.
; CHECK-LABEL: define private void @__instrumentor_ctor() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = alloca x86_fp80, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca [100 x i32], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = call ptr @__instrumentor_pre_global(ptr @A1, ptr @__instrumentor_.str, i64 1, i32 4, i8 0, i8 1) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    store ptr [[TMP2]], ptr @__instrumentor_shadow.A1, align 8
; CHECK-NEXT:    [[TMP3:%.*]] = call ptr @__instrumentor_pre_global(ptr @A2, ptr @__instrumentor_.str.1, i64 2, i32 4, i8 1, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP3]], ptr @__instrumentor_shadow.A2, align 8
; CHECK-NEXT:    [[TMP4:%.*]] = call ptr @__instrumentor_pre_global(ptr @A3, ptr @__instrumentor_.str.2, i64 3, i32 4, i8 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP4]], ptr @__instrumentor_shadow.A3, align 8
; CHECK-NEXT:    [[TMP5:%.*]] = call ptr @__instrumentor_pre_global(ptr @A4, ptr @__instrumentor_.str.3, i64 4, i32 4, i8 1, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP5]], ptr @__instrumentor_shadow.A4, align 8
; CHECK-NEXT:    [[TMP6:%.*]] = call ptr @__instrumentor_pre_global(ptr @A5, ptr @__instrumentor_.str.4, i64 0, i32 0, i8 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP7:%.*]] = call ptr @__instrumentor_pre_global(ptr @A6, ptr @__instrumentor_.str.5, i64 0, i32 0, i8 1, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP8:%.*]] = call ptr @__instrumentor_pre_global(ptr @B1, ptr @__instrumentor_.str.6, i64 0, i32 8, i8 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP8]], ptr @__instrumentor_shadow.B1, align 8
; CHECK-NEXT:    [[TMP9:%.*]] = call ptr @__instrumentor_pre_global(ptr @B2, ptr @__instrumentor_.str.7, i64 0, i32 8, i8 1, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP9]], ptr @__instrumentor_shadow.B2, align 8
; CHECK-NEXT:    [[TMP10:%.*]] = call ptr @__instrumentor_pre_global(ptr @B3, ptr @__instrumentor_.str.8, i64 0, i32 8, i8 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP10]], ptr @__instrumentor_shadow.B3, align 8
; CHECK-NEXT:    [[TMP11:%.*]] = call ptr @__instrumentor_pre_global(ptr @B4, ptr @__instrumentor_.str.9, i64 0, i32 8, i8 1, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP11]], ptr @__instrumentor_shadow.B4, align 8
; CHECK-NEXT:    [[TMP12:%.*]] = call ptr @__instrumentor_pre_global(ptr @B5, ptr @__instrumentor_.str.10, i64 0, i32 0, i8 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP13:%.*]] = call ptr @__instrumentor_pre_global(ptr @B6, ptr @__instrumentor_.str.11, i64 0, i32 0, i8 1, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store [100 x i32] zeroinitializer, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = call ptr @__instrumentor_pre_global_ind(ptr @C1, ptr @__instrumentor_.str.12, ptr [[TMP1]], i32 400, i8 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP14]], ptr @__instrumentor_shadow.C1, align 8
; CHECK-NEXT:    store [100 x i32] zeroinitializer, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = call ptr @__instrumentor_pre_global_ind(ptr @C2, ptr @__instrumentor_.str.13, ptr [[TMP1]], i32 400, i8 1, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP15]], ptr @__instrumentor_shadow.C2, align 8
; CHECK-NEXT:    store [100 x i32] zeroinitializer, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = call ptr @__instrumentor_pre_global_ind(ptr @C3, ptr @__instrumentor_.str.14, ptr [[TMP1]], i32 400, i8 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP16]], ptr @__instrumentor_shadow.C3, align 8
; CHECK-NEXT:    store [100 x i32] zeroinitializer, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = call ptr @__instrumentor_pre_global_ind(ptr @C4, ptr @__instrumentor_.str.15, ptr [[TMP1]], i32 400, i8 1, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP17]], ptr @__instrumentor_shadow.C4, align 8
; CHECK-NEXT:    [[TMP18:%.*]] = call ptr @__instrumentor_pre_global(ptr @C5, ptr @__instrumentor_.str.16, i64 0, i32 0, i8 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP19:%.*]] = call ptr @__instrumentor_pre_global(ptr @C6, ptr @__instrumentor_.str.17, i64 0, i32 0, i8 1, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP20:%.*]] = call ptr @__instrumentor_pre_global_ind(ptr @D1, ptr @__instrumentor_.str.18, ptr [[TMP0]], i32 16, i8 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP20]], ptr @__instrumentor_shadow.D1, align 8
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP21:%.*]] = call ptr @__instrumentor_pre_global_ind(ptr @D2, ptr @__instrumentor_.str.19, ptr [[TMP0]], i32 16, i8 1, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP21]], ptr @__instrumentor_shadow.D2, align 8
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP22:%.*]] = call ptr @__instrumentor_pre_global_ind(ptr @D3, ptr @__instrumentor_.str.20, ptr [[TMP0]], i32 16, i8 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP22]], ptr @__instrumentor_shadow.D3, align 8
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP23:%.*]] = call ptr @__instrumentor_pre_global_ind(ptr @D4, ptr @__instrumentor_.str.21, ptr [[TMP0]], i32 16, i8 1, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP23]], ptr @__instrumentor_shadow.D4, align 8
; CHECK-NEXT:    [[TMP24:%.*]] = call ptr @__instrumentor_pre_global(ptr @D5, ptr @__instrumentor_.str.22, i64 0, i32 0, i8 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP25:%.*]] = call ptr @__instrumentor_pre_global(ptr @D6, ptr @__instrumentor_.str.23, i64 0, i32 0, i8 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    ret void
;
;.
; CHECK: attributes #[[ATTR0]] = { willreturn }
;.
; CHECK: [[META0:![0-9]+]] = !{i32 1, !"wchar_size", i32 4}
; CHECK: [[META1:![0-9]+]] = !{i32 8, !"PIC Level", i32 2}
; CHECK: [[META2:![0-9]+]] = !{i32 7, !"PIE Level", i32 2}
; CHECK: [[META3:![0-9]+]] = !{i32 7, !"uwtable", i32 2}
; CHECK: [[META4:![0-9]+]] = !{i32 7, !"frame-pointer", i32 2}
; CHECK: [[META5:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
;.
