; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --include-generated-funcs --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-file=%S/module_config.json -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "powerpc64le-unknown-linux-gnu"

@A = dso_local global i32 0, align 4

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main() #0 {
  %1 = load i32, ptr @A, align 4
  ret i32 %1
}
;.
; CHECK: @A = dso_local global i32 0, align 4
; CHECK: @llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 1000, ptr @__instrumentor_ctor, ptr null }]
; CHECK: @__instrumentor_.str = private unnamed_addr constant [8 x i8] c"<stdin>\00", align 1
; CHECK: @__instrumentor_.str.1 = private unnamed_addr constant [30 x i8] c"powerpc64le-unknown-linux-gnu\00", align 1
; CHECK: @llvm.global_dtors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 1000, ptr @__instrumentor_dtor, ptr null }]
;.
; CHECK-LABEL: define dso_local i32 @main() {
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr @A, align 4
; CHECK-NEXT:    ret i32 [[TMP1]]
;
;
; CHECK-LABEL: define private void @__instrumentor_ctor() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_pre_module(ptr @__instrumentor_.str, ptr @__instrumentor_.str.1, i32 1) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define private void @__instrumentor_dtor() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_post_module(ptr @__instrumentor_.str, ptr @__instrumentor_.str.1, i32 -2) #[[ATTR0]]
; CHECK-NEXT:    ret void
;
;.
; CHECK: attributes #[[ATTR0]] = { willreturn }
;.
