; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -argpromotion -mem2reg -S | FileCheck %s --check-prefixes=ALL,ARGPROMOTION
; RUN: opt -S -passes='attributor,function(mem2reg)' -aa-pipeline='basic-aa' -attributor-disable=false -attributor-max-iterations-verify -attributor-max-iterations=1 < %s | FileCheck %s --check-prefixes=ALL,ATTRIBUTOR

define internal i32 @deref(i32* %x) nounwind {
; ALL-LABEL: define {{[^@]+}}@deref
; ALL-SAME: (i32 [[TMP0:%.*]])
; ALL-NEXT:  entry:
; ALL-NEXT:    ret i32 [[TMP0:%.*]]
;
entry:
  %tmp2 = load i32, i32* %x, align 4
  ret i32 %tmp2
}

define i32 @f(i32 %x) {
; ALL-LABEL: define {{[^@]+}}@f
; ALL-SAME: (i32 [[X:%.*]])
; ALL-NEXT:  entry:
; ALL-NEXT:    [[TMP1:%.*]] = call i32 @deref(i32 [[X:%.*]])
; ALL-NEXT:    ret i32 [[TMP1]]
;
entry:
  %x_addr = alloca i32
  store i32 %x, i32* %x_addr, align 4
  %tmp1 = call i32 @deref( i32* %x_addr ) nounwind
  ret i32 %tmp1
}
