; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -argpromotion -S | FileCheck %s --check-prefixes=ALL,ARGPROMOTION
; RUN: opt -S -passes=attributor -aa-pipeline='basic-aa' -attributor-disable=false -attributor-max-iterations-verify -attributor-max-iterations=1 < %s | FileCheck %s --check-prefixes=ALL,ATTRIBUTOR

; Don't promote paramaters of/arguments to naked functions

@g = common global i32 0, align 4

define i32 @bar() {
; ARGPROMOTION-LABEL: define {{[^@]+}}@bar()
; ARGPROMOTION-NEXT:  entry:
; ARGPROMOTION-NEXT:    [[CALL:%.*]] = call i32 @foo(i32* @g)
; ARGPROMOTION-NEXT:    ret i32 [[CALL]]
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@bar()
; ATTRIBUTOR-NEXT:  entry:
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call i32 @foo(i32* nonnull align 4 dereferenceable(4) @g)
; ATTRIBUTOR-NEXT:    ret i32 [[CALL]]
;
entry:
  %call = call i32 @foo(i32* @g)
  ret i32 %call
}

define internal i32 @foo(i32*) #0 {
; ALL-LABEL: define {{[^@]+}}@foo
; ALL-SAME: (i32* [[TMP0:%.*]])
; ALL-NEXT:  entry:
; ALL-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
; ALL-NEXT:    call void asm sideeffect "ldr r0, [r0] \0Abx lr \0A", ""()
; ALL-NEXT:    unreachable
;
entry:
  %retval = alloca i32, align 4
  call void asm sideeffect "ldr r0, [r0] \0Abx lr        \0A", ""()
  unreachable
}


attributes #0 = { naked }
