; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes
; RUN: opt < %s -S -ipsccp | FileCheck %s --check-prefixes=ALL,IPSCCP
; RUN: opt -S -passes=attributor -aa-pipeline='basic-aa' -attributor-disable=false -attributor-max-iterations-verify -attributor-max-iterations=1 < %s | FileCheck %s --check-prefixes=ALL,ATTRIBUTOR
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @fn2(i32* %P) {
; IPSCCP-LABEL: define {{[^@]+}}@fn2
; IPSCCP-SAME: (i32* [[P:%.*]])
; IPSCCP-NEXT:  entry:
; IPSCCP-NEXT:    br label [[IF_END:%.*]]
; IPSCCP:       for.cond1:
; IPSCCP-NEXT:    br i1 false, label [[IF_END]], label [[IF_END]]
; IPSCCP:       if.end:
; IPSCCP-NEXT:    [[CALL:%.*]] = call i32 @fn1(i32 undef)
; IPSCCP-NEXT:    store i32 [[CALL]], i32* [[P]]
; IPSCCP-NEXT:    br label [[FOR_COND1:%.*]]
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@fn2
; ATTRIBUTOR-SAME: (i32* nocapture writeonly [[P:%.*]])
; ATTRIBUTOR-NEXT:  entry:
; ATTRIBUTOR-NEXT:    br label [[IF_END:%.*]]
; ATTRIBUTOR:       for.cond1:
; ATTRIBUTOR-NEXT:    br i1 undef, label [[IF_END]], label [[IF_END]]
; ATTRIBUTOR:       if.end:
; ATTRIBUTOR-NEXT:    [[E_2:%.*]] = phi i32* [ undef, [[ENTRY:%.*]] ], [ null, [[FOR_COND1:%.*]] ], [ null, [[FOR_COND1]] ]
; ATTRIBUTOR-NEXT:    [[TMP0:%.*]] = load i32, i32* [[E_2]], align 4
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call i32 @fn1(i32 [[TMP0]])
; ATTRIBUTOR-NEXT:    store i32 [[CALL]], i32* [[P]]
; ATTRIBUTOR-NEXT:    br label [[FOR_COND1]]
;
entry:
  br label %if.end

for.cond1:                                        ; preds = %if.end, %for.end
  br i1 undef, label %if.end, label %if.end

if.end:                                           ; preds = %lbl, %for.cond1
  %e.2 = phi i32* [ undef, %entry ], [ null, %for.cond1 ], [ null, %for.cond1 ]
  %0 = load i32, i32* %e.2, align 4
  %call = call i32 @fn1(i32 %0)
  store i32 %call, i32* %P
  br label %for.cond1
}

define internal i32 @fn1(i32 %p1) {
; IPSCCP-LABEL: define {{[^@]+}}@fn1
; IPSCCP-SAME: (i32 [[P1:%.*]])
; IPSCCP-NEXT:  entry:
; IPSCCP-NEXT:    [[COND:%.*]] = select i1 undef, i32 undef, i32 undef
; IPSCCP-NEXT:    ret i32 [[COND]]
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@fn1
; ATTRIBUTOR-SAME: (i32 returned [[P1:%.*]])
; ATTRIBUTOR-NEXT:  entry:
; ATTRIBUTOR-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[P1]], 0
; ATTRIBUTOR-NEXT:    [[COND:%.*]] = select i1 [[TOBOOL]], i32 [[P1]], i32 [[P1]]
; ATTRIBUTOR-NEXT:    ret i32 [[COND]]
;
entry:
  %tobool = icmp ne i32 %p1, 0
  %cond = select i1 %tobool, i32 %p1, i32 %p1
  ret i32 %cond
}

define void @fn_no_null_opt(i32* %P) #0 {
; IPSCCP-LABEL: define {{[^@]+}}@fn_no_null_opt
; IPSCCP-SAME: (i32* [[P:%.*]])
; IPSCCP-NEXT:  entry:
; IPSCCP-NEXT:    br label [[IF_END:%.*]]
; IPSCCP:       for.cond1:
; IPSCCP-NEXT:    br i1 false, label [[IF_END]], label [[IF_END]]
; IPSCCP:       if.end:
; IPSCCP-NEXT:    [[TMP0:%.*]] = load i32, i32* null, align 4
; IPSCCP-NEXT:    [[CALL:%.*]] = call i32 @fn0(i32 [[TMP0]])
; IPSCCP-NEXT:    store i32 [[CALL]], i32* [[P]]
; IPSCCP-NEXT:    br label [[FOR_COND1:%.*]]
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@fn_no_null_opt
; ATTRIBUTOR-SAME: (i32* nocapture writeonly [[P:%.*]])
; ATTRIBUTOR-NEXT:  entry:
; ATTRIBUTOR-NEXT:    br label [[IF_END:%.*]]
; ATTRIBUTOR:       for.cond1:
; ATTRIBUTOR-NEXT:    br i1 undef, label [[IF_END]], label [[IF_END]]
; ATTRIBUTOR:       if.end:
; ATTRIBUTOR-NEXT:    [[E_2:%.*]] = phi i32* [ undef, [[ENTRY:%.*]] ], [ null, [[FOR_COND1:%.*]] ], [ null, [[FOR_COND1]] ]
; ATTRIBUTOR-NEXT:    [[TMP0:%.*]] = load i32, i32* [[E_2]], align 4
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call i32 @fn0(i32 [[TMP0]])
; ATTRIBUTOR-NEXT:    store i32 [[CALL]], i32* [[P]]
; ATTRIBUTOR-NEXT:    br label [[FOR_COND1]]
;
entry:
  br label %if.end

for.cond1:                                        ; preds = %if.end, %for.end
  br i1 undef, label %if.end, label %if.end

if.end:                                           ; preds = %lbl, %for.cond1
  %e.2 = phi i32* [ undef, %entry ], [ null, %for.cond1 ], [ null, %for.cond1 ]
  %0 = load i32, i32* %e.2, align 4
  %call = call i32 @fn0(i32 %0)
  store i32 %call, i32* %P
  br label %for.cond1
}

define internal i32 @fn0(i32 %p1) {
; IPSCCP-LABEL: define {{[^@]+}}@fn0
; IPSCCP-SAME: (i32 [[P1:%.*]])
; IPSCCP-NEXT:  entry:
; IPSCCP-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[P1]], 0
; IPSCCP-NEXT:    [[COND:%.*]] = select i1 [[TOBOOL]], i32 [[P1]], i32 [[P1]]
; IPSCCP-NEXT:    ret i32 [[COND]]
;
; ATTRIBUTOR-LABEL: define {{[^@]+}}@fn0
; ATTRIBUTOR-SAME: (i32 returned [[P1:%.*]])
; ATTRIBUTOR-NEXT:  entry:
; ATTRIBUTOR-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[P1]], 0
; ATTRIBUTOR-NEXT:    [[COND:%.*]] = select i1 [[TOBOOL]], i32 [[P1]], i32 [[P1]]
; ATTRIBUTOR-NEXT:    ret i32 [[COND]]
;
entry:
  %tobool = icmp ne i32 %p1, 0
  %cond = select i1 %tobool, i32 %p1, i32 %p1
  ret i32 %cond
}

attributes #0 = { "null-pointer-is-valid"="true" }
